-- ============================================================
-- SQL Schema for IoT Automatic Peanut Soil Moisture & Watering System
-- ระบบตรวจวัดความชื้นดินและรดน้ำถั่วลิสงอัตโนมัติด้วย IoT
-- ============================================================

-- 1. Table: sensor_data (ตารางข้อมูลความชื้น อุณหภูมิ ความชื้นอากาศ)
CREATE TABLE IF NOT EXISTS public.sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    soil INT4 NOT NULL,
    temperature FLOAT8,
    humidity FLOAT8,
    pump_status BOOLEAN DEFAULT FALSE
);

ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access to sensor_data" ON public.sensor_data FOR ALL USING (true) WITH CHECK (true);

-- 2. Table: farmer_users (ตารางข้อมูลผู้ใช้งาน/เกษตรกร)
CREATE TABLE IF NOT EXISTS public.farmer_users (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    password VARCHAR(100) DEFAULT 'password123',
    role VARCHAR(20) DEFAULT 'farmer',
    plot_name VARCHAR(100) DEFAULT 'แปลงปลูกถั่วลิสง A1',
    device_id VARCHAR(50) DEFAULT 'ESP32-SOIL-NODE-01',
    status VARCHAR(20) DEFAULT 'active'
);

ALTER TABLE public.farmer_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access to farmer_users" ON public.farmer_users FOR ALL USING (true) WITH CHECK (true);

-- ข้อมูลเกษตรกรถั่วลิสงและแอดมินเริ่มต้น
INSERT INTO public.farmer_users (id, name, email, phone, password, role, plot_name, device_id, status)
VALUES 
('usr-001', 'สมชาย การเกษตร', 'somchai@farm.com', '081-234-5678', 'password123', 'farmer', 'แปลงปลูกถั่วลิสง A1 (พันธุ์ขอนแก่น 60)', 'ESP32-SOIL-NODE-01', 'active'),
('usr-002', 'วิชัย สายเขียว', 'wichai@farm.com', '089-876-5432', 'password123', 'farmer', 'แปลงปลูกถั่วลิสง B2 (พันธุ์ไทนาน 9)', 'ESP32-SOIL-NODE-02', 'active'),
('usr-999', 'ผู้ดูแลระบบ (Admin IoT)', 'admin@beanfarm.io', '02-111-9999', 'admin123', 'admin', 'ศูนย์ควบคุมไร่ถั่วลิสงหลัก', 'MASTER-GATEWAY-01', 'active')
ON CONFLICT (email) DO NOTHING;

-- 3. Table: system_settings (ตารางเกณฑ์ค่ากำหนดระบบ IoT เพื่อให้เว็บกับ ESP32 คุยกันสองทาง)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id INT PRIMARY KEY DEFAULT 1,
    min_soil INT NOT NULL DEFAULT 50,
    target_soil INT NOT NULL DEFAULT 80,
    auto_mode BOOLEAN NOT NULL DEFAULT TRUE,
    max_duration INT NOT NULL DEFAULT 300,
    crop_type VARCHAR(100) DEFAULT 'ถั่วลิสง (Peanut)',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access to system_settings" ON public.system_settings FOR ALL USING (true) WITH CHECK (true);

-- บันทึกค่าเริ่มต้นแถวแรก (id = 1)
INSERT INTO public.system_settings (id, min_soil, target_soil, auto_mode, max_duration, crop_type)
VALUES (1, 50, 80, true, 300, 'ถั่วลิสง (Peanut)')
ON CONFLICT (id) DO NOTHING;

